###
POST http://localhost:7170/api/auth/register
Content-Type: application/json

{
  "email": "finn@email.dk",
  "password": "1234",
  "name": "Finn",
  "phoneNumber": 20623882,
  "roles": ["user", "instructor"]
}


###
POST http://localhost:7170/api/auth/login
Content-Type: application/json

{
  "email": "finn@email.dk",
  "password": "1234"

}

###
GET http://localhost:7170/api/event/upcoming

###
POST  http://localhost:7170/api/event/
Content-Type: application/json

{
  "title": "title",
  "startTime": "startTime",
  "description": "description",
  "LocalDate": "2024-04-22",
  "durationInHour": "100",
  "maxNumberOfStudents": "10",
  "locationOfEvent": "locationOfEvent",
  "instructor": "instructor",
  "price": "100",
  "category": "category",
  "image": "image",
  "Status": "Status.UPCOMING"
}

