###
POST http://localhost:7170/api/auth/register
Content-Type: application/json

{
  "email": "tobias@email.dk",
  "password": "1234",
  "name": "Tobias",
  "phoneNumber": 20623882,
  "roles": ["user", "instructor"]
}


###
POST http://localhost:7170/api/auth/login
Content-Type: application/json

{
  "email": "finn@email.dk",
  "password": "4321"

}

###
GET http://localhost:7170/api/event/upcoming


###
PUT http://localhost:7170/api/events/4
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJMYXVyaXR6IEhhdWdlIiwibmFtZSI6IkZpbm4iLCJzdWIiOiJmaW5uQGVtYWlsLmRrIiwiZXhwIjoxNzEyMjIxOTY0LCJlbWFpbCI6ImZpbm5AZW1haWwuZGsiLCJyb2xlcyI6IixpbnN0cnVjdG9yLHVzZXIifQ.pM6ti0RxeGALYIKp0TVgdkakzEdVD4S0dSGmIz6U1LY
Content-Type: application/json

{
  "title": "title4",
  "startTime": "18:00 pm",
  "description": "Football practice",
  "dateOfEvent": "2024-05-04",
  "durationInHours": 2,
  "maxNumberOfStudents": 44,
  "locationOfEvent": "KFUM Boldkblub Kbh",
  "instructor": "instructor",
  "price": 20.0,
  "category": "Sport",
  "image": "image",
  "status": "UPCOMING"
}


###
PUT http://localhost:7170/api/resetUserPassword
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJMYXVyaXR6IEhhdWdlIiwibmFtZSI6IlRvYmlhcyIsInN1YiI6InRvYmlhc0BlbWFpbC5kayIsImV4cCI6MTcxMjI0MzQ4OCwiZW1haWwiOiJ0b2JpYXNAZW1haWwuZGsiLCJyb2xlcyI6IixpbnN0cnVjdG9yLHVzZXIifQ.GpyPO-lhCjIFP1dyEmQsTaCsiHY9d3_IblUMBejDBvE
Content-Type: application/json

{
  "email": "tobias@email.dk",
  "password": "1234",
  "newPassword": "2222"
}


